name: 🔗 GHA
on:
  workflow_dispatch:

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "**/*.png"
      - "**/*.svg"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "**/*.png"
      - "**/*.svg"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"

jobs:
  static-checks:
    name: 📊 Static checks
    uses: ./.github/workflows/static-checks.yml
    
  gdextension-build:
    name: ⚙️ GDExtension
    needs: static-checks
    uses: ./.github/workflows/gdextension.yml
